### ISSUE TITLE
How to ng-eject?

### ISSUE THREAD

**Issue by bursauxa** [ngx-rocket/generator-ngx-rocket#125]
## I'm submitting a...
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request

## Current behavior
The `build` and `start` tasks are incompatible with ng-eject.
If I remove them to make ng-eject work, then I lose benefits of Rocket's customisations:
- Command arguments --aot and --prod are not accepted by webpack (not sure if it's important or not)
- env2json can be added but I am not entirely sure about what it does, hence I can't verify whether it works
- The proxy configuration is lost and I have no idea how to reuse it in the ejected app

## Expected behavior
Rocket would benefit from having a pre-ejected version, with all tasks properly set up, for those of us who need to meddle with the webpack configuration.

## Environment
Generator version: 4fa02aef7b6bc21bf88be1c148cf7119a0879def
(commit id from branch cordova/ionic of repository starter-kit, 2017-07-13)

**Comment by sinedied** [comment]
Yes, currently using `ng-eject` is not quite easy to use out of the box for now.

>Rocket would benefit from having a pre-ejected version, with all tasks properly set up, for those of us who need to meddle with the webpack configuration.

The issue with going through this behavior is that we lose the ability to benefit from `angular-cli` upgrades, and the main point of going with `angular-cli` is to benefit from its workflow (and upgrades). 
It could eventually be supported by a generator option, but I think it would be best to stick with the current default. Another options is to add a new feature to `ngx-cli` to perform the `ng-eject` and reconfiguration `ngx-rocket` additions properly.

For the questions:
> Command arguments --aot and --prod are not accepted by webpack (not sure if it's important or not)
If I remember well, `ng-eject` creates different configurations for the dev and prod builds. I've never played extensively with it so I can't help much on this, but I bet that choosing the build target could be done through env variables.

> env2json can be added but I am not entirely sure about what it does, hence I can't verify whether it works
It exports env variables to a json file, see https://github.com/ngx-rocket/scripts#export-environment-variables-to-a-json-file (used essentially to import `package.json` version into the app, but can be used for other things)

> The proxy configuration is lost and I have no idea how to reuse it in the ejected app
Since webpack is used directly after eject, the `webpack-dev-server` is also used for the developement. You can specify the proxy configuration by adding a new `devServer` entry to the webpack build configuration with the `proxy` property set, see https://webpack.github.io/docs/webpack-dev-server.html#api

**Comment by ggaulard** [comment]
doing an eject with the original angular-cli does the job I have to update the CopyWebpackPlugin 
      {
        "context": "src",
        "to": "",
        "from": {
          "glob": "src/assets/**",
          "dot": true
        }
      },

there was a src/ to remove

**Comment by bursauxa** [comment]
Thanks @ggaulard, I think that answers my question. Possibly there were some changes since my attempt, as several months went by.
