### ISSUE TITLE
Update to Angular 5

### ISSUE THREAD

**Issue by AmmarHasan** [ngx-rocket/generator-ngx-rocket#164]
Angular 5 has been officially released, so we should migrate to the new version

**Comment by sinedied** [comment]
Sure ! We have to update with latest angular-cli also, and enable aot in serve mode as recommended.

**Comment by sinedied** [comment]
The code needed for Angular@5 has been pushed, but won't be merged immediately because there is pending issues on `@angular/cli` which prevents proper usage:
- https://github.com/angular/angular-cli/issues/8359#issuecomment-342092153
- https://github.com/angular/angular-cli/issues/6650

Also for reference, `@angular/service-worker` cannot be updated to `@5.0.0` because of https://github.com/angular/angular-cli/issues/8247 and we cannot migrate to the new `HttpClient` API because of https://github.com/angular/angular/issues/18155, so we are stuck with the deprecated `Http` service for now 😞
