### ISSUE TITLE
Update to Angular CLI 1.6 and TypeScript 2.5

### ISSUE THREAD

**Issue by gaetanmaisse** [ngx-rocket/generator-ngx-rocket#200]
With Angular 5.1 release, it now supports TypeScript 2.5. Angular team also ship a new version of Angular CLI so it's time to update generator!

**Comment by sinedied** [comment]
The PR is ready, but this issue is problematic with ionic: https://github.com/angular/angular-cli/issues/8781

The workaround is not applicable as it breaks the build, so it's currently stuck with (a lot) of warning, despite the fact that it's working.

Should I make the release with that anyways, or postpone it until a fix or proper workaround is found? Any thoughts?
