### ISSUE TITLE
Redundancy in route

### ISSUE THREAD

**Issue by 110692** [ngx-rocket/generator-ngx-rocket#204]
As I am developing enterprise level application I feel that I need to define routes two times 
in header section and module route section 
can we improve this????

just throwing an idea. :)

**Comment by nileshpatilwork** [comment]
@sinedied any comment on this?

**Comment by sinedied** [comment]
If you want you can iterate from the route definitions to display the links in the header, but you won't gain much and you will introduce tight coupling. 
As the route may be defined on lazy-loaded modules and because you may not always want to show a header link when a new module is added, I think that we cannot do fundamentally better than the current solution using loose coupling.

**Comment by bursauxa** [comment]
Closing this as @110692 thumbed-up the answer.
