### ISSUE TITLE
Implement ngx-bootstrap

### ISSUE THREAD

**Issue by nileshpatilwork** [ngx-rocket/generator-ngx-rocket#232]
Hi @sinedied 
Could you please implement [ngx-bootstrap](https://valor-software.com/ngx-bootstrap/#/getting-started) so we can use common components very easily in enterprise application.

**Comment by sinedied** [comment]
Hello, we chose [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) over ngx-bootstrap because of higher quality components (the team behind it made `angular-ui-bootstrap` for AngularJS) and Bootstrap 4 only support (no legacy code).

We do no plan to switch library at this point, but if you need it you can always [make an addon](https://github.com/ngx-rocket/generator-ngx-rocket/tree/master/generators/addon) to override the Bootstrap template with ngx-bootstrap component instead of ng-bootstrap ones.
