### ISSUE TITLE
tree shaking

### ISSUE THREAD

**Issue by lakshmajim** [ngx-rocket/generator-ngx-rocket#296]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Expected behavior

Support of **tree-shaking** with **rollupjs** to reduce product build size

## Environment

```
- generator version: 1.0.0
- node version: 8.9.4 
- npm version: 5.6.0  
- OS:  Mac 
```

**Comment by sinedied** [comment]
Angular CLI already has support for tree shaking, so I don't really see what additional benefits we could get from Rollup?

Besides, we don't plan to move away from Angular CLI anytime soon, and it's based on webpack so you would need to rewrite the whole toolchain to make it work.

You can try to give it a go by creating an [add-on](https://github.com/ngx-rocket/generator-ngx-rocket/tree/master/generators/addon) for to support it, maybe using https://github.com/steveblue/angular2-rollup?

**Comment by lakshmajim** [comment]
Hi @sinedied , Thank you very much for reply.
I agree with you and I am not saying e will move away from angular cli (it has evolved since initial release).

If we add support of  rollupjs or tree-shaking, the production build size will be reduced. Here I' have found article floating around the web [How to reduce production build size](http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/).

If the build size was reduced the angular application will loads at lightening speed (May be not the speed of light :stuck_out_tongue_winking_eye: ).

**Comment by sinedied** [comment]
The linked article is from 2016, when at this time tree-shaking was not enabled in Angular CLI, and CLI was not even using webpack but Brocoli as its bundler 😉 

Angular CLI has changed a lot since then, and tree shaking is now enabled for production, along with a special build optimizer that reduces bundle size even more, see https://github.com/angular/angular-cli/wiki/build#bundling--tree-shaking

Rollupjs was evoked as this time as a bundler replacement because it was doing tree shaking when Brocoli did not and webpack support for it was just beginning. Now that tree shaking is properly supported in webpack (and then in Angular CLI), using Rollupjs would not change much and would even do worse, as Angular's dedicated build optimized makes the tree shaking more efficient.

**Comment by lakshmajim** [comment]
So, You are saying ```bash npm run build --env=prod``` does all magic (with [ngx-rocket](https://github.com/ngx-rocket/generator-ngx-rocket)), which has included AOT and some build optimisations.

**Comment by sinedied** [comment]
@lakshmajim Yes, and `npm run build` use `prod` option by default so you don't even need to specify it.

**Comment by lakshmajim** [comment]
@sinedied , Thank you sooo much.... for sharing this info.

**Comment by lakshmajim** [comment]
We can close this ticket
