### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by nileshpatilwork** [ngx-rocket/generator-ngx-rocket#304]
facing below issue after implementing lazy loading.
![capture](https://user-images.githubusercontent.com/27280585/38470428-350dfae0-3b80-11e8-9cfc-fbdcc9151fd4.PNG)

**Comment by sinedied** [comment]
@nileshpatilwork Please follow the issue template so we can help you, we need a bit more context such as OS, version etc as in the template.

Seems related to https://github.com/angular/angular-cli/issues/9775

**Comment by nileshpatilwork** [comment]
I am using Windows 7, Angular 5.2.5, ngx-generator 4.1.0
I can see about.module.chunk.js loaded initially when app loaded. Please check below image.
![capture](https://user-images.githubusercontent.com/27280585/38611364-190355d4-3da1-11e8-848c-dae32689e71e.PNG)

**Comment by sinedied** [comment]
That's not a bug, that's by design look at `app-routing.module.ts`:
```ts
  imports: [RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })],
```
The default strategy is to preload all modules, so get the best of both worlds:
- Only the needed modules are first loaded to ensure fast initial screen display
- Remaining modules are then preloaded so later navigation is faster

You can change this behavior or implement your own if needed, see https://medium.com/@adrianfaciu/custom-preloading-strategy-for-angular-modules-b3b5c873681a for more details.
