### ISSUE TITLE
How to run Ionic commands

### ISSUE THREAD

**Issue by lgadola** [ngx-rocket/generator-ngx-rocket#316]
How can I run a Ionic command like "ionic generate" or "ionic cordova resources"?
Ionic CLI does not recognize the project as ionic project and therefore throws an error

**Comment by sinedied** [comment]
You cannot use ionic cli for now, it will work after the release of ionic@v4 as it's announced to be compatible with angular-cli.

Instead of `ionic generate` you can use `ngx generate` with any of the https://github.com/angular/angular-cli command. 

However to use `ionic cordova resources` you can trick ionic to think it's a ionic project by adding a `ionic.config.json`:
```
{
  "name": "anything",
  "app_id": "",
  "type": "ionic-angular",
  "integrations": {}
}
```
and it should work.

**Comment by lgadola** [comment]
thanks, I'll try it
