### ISSUE TITLE
Visual Studio Code Debugging

### ISSUE THREAD

**Issue by lgadola** [ngx-rocket/generator-ngx-rocket#319]
Great project!
I managed to debug using VS Code and Chrome debugger.
However, trying android debugging results in "breakpoint ignored because generated code not found (source map problem?)

Launch.json:

`    "configurations": [
        {
            "name": "Attach to android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator-5554",
            "port": 9222,
            "cwd": "${workspaceRoot}",
            "sourceMaps": true
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]`

**Comment by sinedied** [comment]
How did you run the app on android? The default `cordova:run` command builds the app for production, so there is no sourcemaps.
To debug on android, you may try to create a new `build:dev` script in `package.json` without the `--prod` flag, and use is in the `cordova:run` script instead of the `build` script for production.

**Comment by bursauxa** [comment]
@lgadola was the above information of any help?

**Comment by lgadola** [comment]
throws:
> ngx-scripts cordova run --dev  "android"

Unknown option: '--dev'

**Comment by sinedied** [comment]
Closing as it's been a while, feel free to comment if you still have issues.
