### ISSUE TITLE
module lazy loading

### ISSUE THREAD

**Issue by leihg** [ngx-rocket/generator-ngx-rocket#322]
Hello, how do you do the module lazy loading?

**Comment by sinedied** [comment]
I don't quite understand the question? If you generate a new project with the latest version, you have a question asking if you want lazy loading or not (expect if you choose Ionic for the UI as it's incompatible for now).

**Comment by leihg** [comment]
My present project is a project generated by this tool, but it is too slow to be loaded for the first time, the login module that is first loaded, and the rest of the modules are also loaded, causing the entry of the login module too slow. Is there any way to enter the login module without loading other modules to express the login page quickly, thanks

**Comment by sinedied** [comment]
In that case, you should indeed activate lazy loading on all the modules that are not needed to display the login page, see https://angular.io/guide/lazy-loading-ngmodules.

If you want an example, you can generate a new project with lazy loading enabled and take a look at the `about` module, which is lazy loaded by default.
Note that the default strategy is to preload all modules, which should be fine since the loading of other modules will come after the login is displayed in your case, but if you want to change that see: https://github.com/ngx-rocket/generator-ngx-rocket/issues/304#issuecomment-381879649

**Comment by leihg** [comment]
The problem has been solved, thank you very much!
