### ISSUE TITLE
Unable to add role guard to the route using current route structure 

### ISSUE THREAD

**Issue by 231293** [ngx-rocket/generator-ngx-rocket#328]
using below method unable to add role guard to the route.

export class Route {
  static withShell(routes: Routes): ngRoute {
}
}

As enterprise level app we should provide a way to safe route using role guard,
Please help.

**Comment by sinedied** [comment]
Please give us a bit more context so that we can help you, I dont see anything with the code you shared, and I'm not sure I understand what you're trying to do.

You can take a look at the authentication guard if you want an example, see https://github.com/ngx-rocket/starter-kit/blob/master/src/app/core/route.service.ts for its usage in routes.

**Comment by bursauxa** [comment]
Closing this due to lack of information.
