### ISSUE TITLE
App doesn't update source code after npm run cordova

### ISSUE THREAD

**Issue by adappter** [ngx-rocket/generator-ngx-rocket#350]
## I'm submitting a...

- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
If I run `npm run cordova run browser` the app correctly starts in browser.
After I make some changes in my source code and run the same command, the app doesn't update.
Best to see with css changes.
Same for `npm run cordova run ios` and `android`
With `npm start` the changes are immediately.

## Expected behavior
Changes made on source code should be visible after `npm run cordova run browser` command

## Environment

```
- generator version: 5.0.1
- node version: 10.4.1
- npm version: 6.2.0
- angular-cli version: 6.0.8 
- OS:  MAC
```

**Comment by sinedied** [comment]
It's not a bug, the feature is not implemented, see https://github.com/ngx-rocket/generator-ngx-rocket/issues/108

Despite my initial thoughts on the issue, it's not quite trivial to implement 😞

**Comment by adappter** [comment]
But what I mean is not the live-reload. 
I don't have a problem if live-reload is not possible.
My problem is, wether I `run npm run cordova browser` my source code doesn't change. Also after removing platform and re-add.

**Comment by adappter** [comment]
I think `npm run cordova:prepare` is the solution...

**Comment by sinedied** [comment]
Ok, I misunderstood the issue then I reopened it.

The issue is that you have to use our support scripts through the `npm run cordova:(ios|android)` (and you can add your own for browser) and not `npm run cordova run ...` directly, as like this the JS app doesn't get rebuilt. You can test it easily by running the build script manually `npm run build` before your commands.

That's why we created the support scripts, so the JS build + cordova build can be done in a single step :wink:

**Comment by sinedied** [comment]
@adappter Did my previous post answer your question?

**Comment by adappter** [comment]
Yes sorry, forgot to close!
