### ISSUE TITLE
Feature request: single e2e test run support

### ISSUE THREAD

**Issue by captaincaius** [ngx-rocket/generator-ngx-rocket#392]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior

Generated apps can't run a single e2e spec from the commandline too easily.

## Expected behavior

You can run a single spec without hacking protractor conf manually

Is there any interest in supporting this?

**Comment by sinedied** [comment]
Since the tests are written in jasmine you can always prefix the test or test suite by `f` (ie `fdescribe` or `fit`), or from the CLI you can use the `--specs` option it seems: https://github.com/angular/protractor/issues/164

Using angular-cli e2e command, it seems you can only specify a `--suite` and not a single test: https://github.com/angular/angular-cli/wiki/e2e

**Comment by captaincaius** [comment]
well the way I've been doing it is that I keep a protractor-single.conf, a protractor.conf, and a protractor-common.conf - it's not pretty, but it avoids the risk of someone accidentally missing a PR with "fdescribe" or something similar on it.

I've been keeping protractor-single in .gitignore, but I think nowadays it can be done with a commandline parameter or an environment variable instead of manually hacking the specs in -single.conf.

But ok if you think it's yagni, we can close this ;).
