### ISSUE TITLE
Question: HTTP caching interceptor, setting entries to expire after 30 minutes

### ISSUE THREAD

**Issue by nvella88** [ngx-rocket/generator-ngx-rocket#408]
Good afternoon,

Firstly, I would like to thank you for the product you are offering. It is helping us a lot in our development.
I am using HTTP-cache.service.ts and would like to know how best to set a 30-minute expiration on cache entries. Which place is best to put this logic?

**Comment by sinedied** [comment]
The best place would be in my opinion in the cache service itself: https://github.com/ngx-rocket/starter-kit/blob/master/src/app/core/http/cache.interceptor.ts#L37

Instead of just getting the cached data, you can make a new methods that check for how long the data has been cached before returning it back, and simply clear cache and return null instead of cached data if it has been there for longer than 30min.

**Comment by bursauxa** [comment]
Looks like you understood that perfectly 😃

**Comment by nvella88** [comment]
Thank you very much!
