### ISSUE TITLE
Use localStorage `setItem` and `getItem` instead of `this.storage[cachePersistenceKey]`

### ISSUE THREAD

**Issue by jogelin** [ngx-rocket/generator-ngx-rocket#410]
# I'm submitting a...
- [ X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
When I setup the Jest configuration in the generated project, I have an error on the `localStorage` usage in `src/app/core/http/http-cache.service.ts`. 

Actually, Jest in mocking the `localStorage`and the `http-cache.service.ts` is not using the methods `setItem` and `getItem` but instead, it is using `this.storage[cachePersistenceKey]`....

## Expected behavior
Use the methods `setItem` and `getItem` to communicate with the `localStorage`

```
  private saveCacheData() {
    if (this.storage) {
      this.storage.setItem(cachePersistenceKey, JSON.stringify(this.cachedData));
    }
  }

  private loadCacheData() {
    const data = this.storage ? this.storage.getItem(cachePersistenceKey) : null;
    this.cachedData = data ? JSON.parse(data) : {};
  }
```

**Comment by bursauxa** [comment]
Apparently the keyed accessor is not part of the standard ([MDN](https://developer.mozilla.org/fr/docs/Web/API/Storage)) so we should really make that change.

@jogelin thanks for the report, since you have already identified the fix maybe you want to submit a PR for it yourself ? If for some reason you do not want to, I will do it myself, but you might as well take credit.
