### ISSUE TITLE
environments and proxy config expansion

### ISSUE THREAD

**Issue by captaincaius** [ngx-rocket/generator-ngx-rocket#414]
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior

Just wanted to see your thoughts on whether it's worthwhile to add more bells and whistles to the current environment / proxy setup...  The current setup is already pretty awesome and a pretty good balance, so this might be overkill, but I wanna run it by you anyway.

I'm migrating my project over now (yay!!) and wanted to see if some of my setup is worth including or if it's too specific...  Some of this might not be so useful unless the project is part of a full stack project

If you think any of this is worthwhile, I'd be happy to work on it after we discuss specifics :)

## Expected behavior

Specific changes I propose:

- changing the /api to /api-norris (to distinguish between external APIs and ones own, and so there's less to change when setting up).
- splitting what's currently "serverUrl" in the environment into three:
  - one (again) for external APIs
  - one for your "own" API
  - another for frontend URLs (for example, if you need to build absolute URLs to show users, they won't be the same as what the HTTP interceptor will use).
- adding a qa configuration to angular.json that's for building similar to prod, but maybe with slightly different settings (e.g. sourceMaps true)
- move proxy config to angular.json so you can separate proxy configurations for different environments (dev vs test/e2e so you can run tests against a separate backend while developing while e2e is running, you can have a clean DB, etc)
- more environments out of the box (e.g. qa as mentioned, and one for e2e for things like using a recaptcha test key or disabling animations when doing e2e)
- removal of the redundant .env stuff?  It's not a big deal, but I worry that it might give people a false sense of security that it's safe to put secrets in there because I've literally seen articles suggesting that as a motivation :(.  Or maybe I'm misunderstanding its purpose.

...um, that's all I got so far ;) maybe I'll come up with more when I'm done.  LMK what you think :).

## Environment

```
- generator version: X.Y.Z
- node version: X.Y.Z  <!-- run `node --version` -->
- npm version: X.Y.Z  <!-- run `npm --version` -->
- OS:  <!-- Mac, Linux, Windows -->
```

Others:

**Comment by sinedied** [comment]
There a lot here so I'll try to answer it all, with my own opinion 😉 

> changing the /api to /api-norris (to distinguish between external APIs and ones own, and so there's less to change when setting up).

I'm not sure it's a good thing, as the idea is to force the user to update it anyway and not keep this example API forever: the example is external for the sake of simplicity, but may be later changed by a mock server (an idea I've yet to propose) and the aims is to use it for internal API.

For external APIs, you don't need a proxy anyways as you fall in the classic 3rd party calls use case, meaning CORS should be enabled on the target server (the API proxy is there because of CORS issues with internal APIs initially).

> splitting what's currently "serverUrl" in the environment into three

- For external (3rd party) APIs, see my previous answer ;) For the interceptor prefix, it can be skipped either explicitely (`http.disableApiPrefix().get('/api-other/some-api')`) or implicitely by using an absolute URL with `http[s]://`.
- For other URLs builds manually, it's not really the purpose of the `serverUrl` config I think (maybe the name is not explicit enough though):
  * it's just for build links you can add a new env constant
  * if it's for other API calls, then it's just like 3rd party APIs in my opinion

> adding a qa configuration to angular.json that's for building similar to prod, but maybe with slightly different settings (e.g. sourceMaps true)

> more environments out of the box (e.g. qa as mentioned, and one for e2e for things like using a recaptcha test key or disabling animations when doing e2e)

We were once considering going all the way with 4-stages configs (dev / qa / preprod / prod), but differents have many differents to manage their various environments and naming them, so we preferred to avoid bloating this and kept things simple with just dev / prod, letting anyone managing their additional envs as they see fit.

> move proxy config to angular.json so you can separate proxy configurations for different environments (dev vs test/e2e so you can run tests against a separate backend while developing while e2e is running, you can have a clean DB, etc)

I'm not sure I understand your meaning exactly, or how you would do that? In my current project we have multiple api proxy configs like `proxy-preprod.conf.js`, `proxy-staging.conf.js` etc and just use different npm scripts to choose which one of them to use. This is even more flexible I think as I can proxy API calls to preprod whether I use a dev or prod build config, but maybe I missed something?

> removal of the redundant .env stuff? It's not a big deal, but I worry that it might give people a false sense of security that it's safe to put secrets in there because I've literally seen articles suggesting that as a motivation :(. Or maybe I'm misunderstanding its purpose.

The `.env` file is generated (and overwritten) by ngx-scripts through the `env` npm task, and it's  simply to expose environment variables as JSON for any usage you might want, like displaying the version or getting extra config from your CI bot, etc.
It could be a good idea to write some doc on this though to explain its purpose.

As for secrets, using environments variables have a good track record for avoiding to put thing like API tokens and such directly in your public git repo, and letting the CI expose it at build time, it's a common practice. Still, you have to keep in mind that it's just for git and anything put in there ends up in your bundle in plain text, like with any other JS 😄

**Comment by captaincaius** [comment]
Thanks so much for taking the time to reply to my suggestions :).

- About /api-norris, oops - :man_facepalming: you wouldn't even need a proxy for external APIs.  Sorry for the noise.

- About the ".env" stuff - yeah it seems I totally misunderstood its purpose.  I saw the name and thought it's something related to server-side .env, like https://www.npmjs.com/package/dotenv but on the client side.  Your explanation was perfect - for saving build-time process environment variables into the app environment.  Handy!  So actually it's kind of the reverse of the dotenv package (making server-side secrets from a file appear as process environment variables).

So ya, maybe documenting it a little will help (I won't post one of the links that frightened me, but imagine you didn't know what ngx-rocket's .env was for, and google "dotenv angular medium" and you'll see one).  I looked around for a good place, and maybe a little comment in environment.ts might be a good start.

- about the qa/preprod/prod/staging/whatever in angular.json - ya you're right - I can see it getting too opinionated.  It's easy enough to copy production to qa and turn on sourceMap for anyone that wants it.

- about the proxy stuff, yeah exactly - I mean something similar to what you're saying, but for dev and e2e.  In proxy-e2e.conf.js I'm proxying to localhost:7357 and for dev I'm proxying to locahost:9000 ... I guess in my case I missed how you did it without angular.json surgery (i.e. adding an e2e configuration to app:serve, changing the e2e target correspondingly, etc).  I guess I overcomplicated things - I'll google for a simpler approach.

- the only thing I don't think I explained clearly was the serverUrl thing - and yeah, it's just a naming thing... apiUrl would be better.  In my case I need the URL the user sees for "copy your profile URL" functionality, and that's gonna be a different URL than the one for the API interceptor, so I've got a separate environment-specific API_URL and BROWSER_URL (forgive the nasty all-caps :P).  Sure I could get it from the current URL, but IMO it's cleaner and my backend needs it anyway.

I guess I'll close this.  I'll try to PR some comments to explain the .env thing soon if you think it's worthwhile.
