### ISSUE TITLE
Ng-Zorro

### ISSUE THREAD

**Issue by ltotsas** [ngx-rocket/generator-ngx-rocket#443]
Can somebody help me add ng-zorro?  i am struggling a bit here :D

**Comment by 6matko** [comment]
It would be easier if you described where are you struggling ? I remember that I had some issues with it as well, but I solved them (Also don't remember how).

**Comment by 6matko** [comment]
Quick update to this question if somebody will be needing in future. I needed to add Ng zorro to my app once again and everything went quite smooth. What did I do:
1. Used `ng add ng-zorro-antd --i18n=en_US` from https://ng.ant.design/docs/introduce/en
2. Since I am using Sass and NgZorro using Less I needed to get those styles to my project as well so I created **theme.less** in **src** folder with following content: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/scripts/site/_site/doc/theme.less
3. Added `src/theme.less` to angular.json (styles):
```
            "styles": [
              "src/theme.less",
              "src/main.scss"
            ],
```
4. Used `NgZorroAntdModule` where I need it

Hope it helps and if there any particular errors then those are custom cases that need custom solutions.
