### ISSUE TITLE
do a request but not with api prefix 

### ISSUE THREAD

**Issue by Paul75** [ngx-rocket/generator-ngx-rocket#487]
##I'm submitting a...

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

## Current behavior
I want to do a request but with no prefix request. I want to directly do with url....

**Comment by LuisReinoso** [comment]
Hi, you could try any http request adding without prefix adding

```
this.http.disableApiPrefix().get(...)
```

**Comment by Paul75** [comment]
> Hi, you could try any http request adding disableApiPrefix() to send request without prefix
> 
> ```
> this.http.disableApiPrefix().get(...)
> ```

Hello, the function disableApiPrefix() not found ....

**Comment by Paul75** [comment]
I not have because I don't update the ngx-rocket for long time ...

And my version is obsolete but now I can't upgrade rapidly.

I modify the http.service.ts with the last version contain it .

No more need ?

**Comment by bursauxa** [comment]
URLs that are specified with a full path, meaning they start with `http://` or `https://`, are ignored by the API prefix interceptor. This should likely cover your use case.

This change is in effect since commit 29db880 (July 2018). Note that the change was made in `api-prefix.interceptor.ts`, not in `http.service.ts`.
