### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jycouet** [ngx-rocket/generator-ngx-rocket#52]
Hi, 
I wanted to look a bit at the generator... and maybe help... But I can't find how to start with it.
How is your environment?
How do you test the generator itself?

In the README.md of this repo, we can learn how to use the generator. But not how to develop/contribut.
Could you write somehting about it please?

Thank you

**Comment by sinedied** [comment]
It's definitely something that needs to be done, I'll try to put something up quickly.

Just to get you started, I'm working on OS X with WebStorm IDE, but nothing fancy is required beside NodeJS/Git and a shell (bash if possible) for the scripts.
For the testing your can take a look at `scripts/test.sh`, basically it use json files to describe the tests cases via possible generator options, then generates projects using the `--automate` option then run `build`, `e2e` and `test:ci` tasks.

**Comment by R0muald** [comment]
I would also be interested to start working on the mobile generator. 
Since it's going to be a feature branch, do you prefer us to clone the repo then directly commit to the feature branch then make a PR from there, or do you prefer that we make a fork, then do a PR from our branch?

**Comment by R0muald** [comment]
@jycouet, Maybe you already know about it but once you have a local copy of the generator, you can use `npm link` from that folder so it will link the project to the global npm.
From there, if you use `yo ngx-app` from any folder, it will use your local version. 
Make things easy to test...

**Comment by sinedied** [comment]
The docs are in progress, I've got a lot to rollup before my holidays, but I'll try to pull up a first version before taking a break ;-)

@R0muald I think the best is a mix of both, since I know some collaborators also interested into working on the mobile version: I'll create a feature branch tomorrow (have some bits to merge before), then you can fork the repo and submit PR to this branch, and everyone will do the same.
We also need to split the job into separate issues to avoid duplicate work.

**Comment by sinedied** [comment]
Feel free to review and suggest changes to the PR before I merge it 😉
