### ISSUE TITLE
vulnerability

### ISSUE THREAD

**Issue by deniskkk** [ngx-rocket/generator-ngx-rocket#82]
Is this [vulnerability](https://snyk.io.cnpmjs.org/test/npm/generator-ngx-rocket) still present?

**Comment by sinedied** [comment]
The issue is related to [yeoman-generator](https://snyk.io.cnpmjs.org/test/npm/yeoman-generator), you should post the issue on their repository, but I doubt they will fix it.

This is issue is only tool-related, and I bet `shelljs` is needed to generate projets in a cross-platform way. This vulnerability is however not present in the *generated projects*, which is what's important here.

**Comment by deniskkk** [comment]
but still `shelljs` present in projects `node_modules` folder

**Comment by sinedied** [comment]
> but still shelljs present in projects node_modules folder

not in the generated project folder? Since `generator-ngx-rocket` should be installed globally and used only to generate the project boilerplate,`shelljs` is not present in the generate projects which is what's really relevant here since it's the project which ends up deployed in the cloud. See the report on the [starter kit](https://snyk.io/org/sinedied/project/4602f5d5-58b3-4973-988c-f5039fa9a555) generated project, no vulnerabilities here.

I understand you concern and you're right to ask the question, but here the vulnerability is not really relevant in the case of a *local* CLI tool, it's like saying having a shell installed makes you vulnerable because you can execute system commands on it ;)

**Comment by deniskkk** [comment]
sorry for misunderstanding in my previous post. `shelljs` present in **generated** projects `node_modules` folder

**Comment by sinedied** [comment]
My bad, I just took a look at it and `shelljs` is used by CLI tools used for development, not production: [htmlhint](https://snyk.io.cnpmjs.org/test/npm/htmlhint) used to lint HTML code, and in the WIP code including upcoming mobile features with [cordova](https://snyk.io.cnpmjs.org/test/npm/cordova) used to build the mobile app.

It is part of the `devDependencies`, meaning that using `npm install --production` for installing `node_modules` relevant only for production (and not development process) omits `shelljs`. That's also why snyk does not mark the generated projects as vulnerable, as it's only used for development.
